CREATE TABLE IF NOT EXISTS "movies" (
	"id" text PRIMARY KEY NOT NULL,
	"original_title" text NOT NULL,
	"primary_title" text NOT NULL,
	"description" text,
	"type" text,
	"start_year" integer,
	"end_year" integer,
	"runtime_minutes" integer,
	"budget" bigint,
	"gross_worldwide" bigint,
	"content_rating" text,
	"is_adult" boolean,
	"average_rating" numeric(3,1),
	"metascore" integer,
	"num_votes" integer,
	"countries_of_origin" text[],
	"filming_locations" text[],
	"genres" text[],
	"interests" text[],
	"spoken_languages" text[],
	"external_links" text[],
	"production_companies" json,
	"release_date" date,
	"primary_image" text,
	"trailer" text,
	"url" text
);