CREATE TABLE IF NOT EXISTS "books" (
	"id" integer PRIMARY KEY NOT NULL,
	"etag" varchar(255),
	"title" text,
	"subtitle" text,
	"authors" jsonb,
	"published_date" varchar(10),
	"description" text,
	"isbn_10" varchar(20),
	"isbn_13" varchar(20),
	"page_count" integer,
	"print_type" varchar(50),
	"categories" jsonb,
	"maturity_rating" varchar(50),
	"allow_anon_logging" boolean,
	"content_version" varchar(50),
	"image_small_thumbnail" text,
	"image_thumbnail" text,
	"language" varchar(10),
	"preview_link" text,
	"info_link" text,
	"canonical_volume_link" text,
	"sale_country" varchar(10),
	"saleability" varchar(50),
	"is_ebook" boolean,
	"viewability" varchar(50),
	"embeddable" boolean,
	"public_domain" boolean,
	"text_to_speech_permission" varchar(50),
	"epub_available" boolean,
	"pdf_available" boolean,
	"access_view_status" varchar(50),
	"quote_sharing_allowed" boolean,
	"snippet" text
);