CREATE TABLE IF NOT EXISTS "users" (
	"id" integer PRIMARY KEY NOT NULL,
	"first_name" text,
	"last_name" text,
	"maiden_name" text,
	"age" integer,
	"gender" text,
	"email" text,
	"phone" text,
	"username" text,
	"password" text,
	"birth_date" text,
	"image" text,
	"blood_group" text,
	"height" double precision,
	"weight" double precision,
	"eye_color" text,
	"hair" jsonb,
	"address" jsonb,
	"company" jsonb,
	"bank" jsonb,
	"crypto" jsonb,
	"ip" text,
	"mac_address" text,
	"university" text,
	"ein" text,
	"ssn" text,
	"user_agent" text,
	"role" text
);